/* GPS Viewer v66 address normalization + automatic text/icon fitting + weather extras. */
(function(){
function text(id){return(document.getElementById(id)?.textContent||'').trim()}
function ensureCountryLine(){const card=document.querySelector('.address-card'),content=card?.querySelector('.address-content');if(!content)return;let country=document.getElementById('addressLine4');if(!country){country=document.createElement('div');country.id='addressLine4';country.className='address-line';country.textContent='India';content.appendChild(country)}let saved=null;try{saved=JSON.parse(localStorage.getItem('gpsViewer.lastAddress')||'null')}catch(e){}const house=document.getElementById('addressLine2'),area=document.getElementById('addressLine3');let houseText=String(saved?.line2||'').trim();if(!houseText){const current=text('addressLine2');if(current&&!/^India$/i.test(current))houseText=current}if(house&&houseText)house.textContent=houseText;if(house)house.style.display=houseText?'block':'none';if(area){let s=text('addressLine3').replace(/\s*,\s*India\s*$/i,'').trim();area.textContent=s}country.textContent='India';country.style.display='block';country.style.visibility='visible'}
function fitElement(el,max,min){if(!el)return;const computed=getComputedStyle(el),base=parseFloat(computed.fontSize)||max;let size=Math.min(max,base);el.style.fontSize=size+'px';el.style.whiteSpace='nowrap';let guard=0;while(el.scrollWidth>el.clientWidth+.5&&size>min&&guard++<20){size=Math.max(min,size-.25);el.style.fontSize=size+'px'}}
function fitDashboardText(){document.querySelectorAll('.position-grid .metric-label,.weather-grid .metric-label').forEach(el=>fitElement(el,13.5,10.5));document.querySelectorAll('.position-grid .metric strong,.weather-grid .metric strong').forEach(el=>fitElement(el,13.5,10.5));document.querySelectorAll('.weather-main .condition').forEach(el=>fitElement(el,13.5,11))}
function moonPhase(){const known=new Date(Date.UTC(2000,0,6,18,14,0));const days=(Date.now()-known.getTime())/86400000;return((days%29.530588853)+29.530588853)%29.530588853/29.530588853}
function moonSVG(phase,cloud){const p=Math.round(phase*8)%8, waxing=phase<.5, full=p===4,newMoon=p===0;const moon=newMoon?'':`<circle cx="42" cy="39" r="27" fill="#ffe47a"/><circle cx="${waxing?'52':'32'}" cy="39" r="27" fill="#151a25"/>`;const fullMoon=full?'<circle cx="42" cy="39" r="27" fill="#ffe47a"/>':'';const cloudPart=cloud?'<path d="M16 65c0-8 7-14 15-14 3-10 12-17 23-17 13 0 24 9 27 21 8 0 15 6 15 14 0 8-7 14-15 14H32c-9 0-16-7-16-18z" fill="#f0f4f8" stroke="#c7d0da" stroke-width="2"/>':'';return`<svg class="modern-weather-icon" viewBox="0 0 112 92" aria-hidden="true"><g>${moon||fullMoon}${cloudPart}</g></svg>`}
function daySVG(cloud){const c=cloud?'<circle cx="38" cy="38" r="18" fill="#ffe45b"/><path d="M18 64c0-8 7-14 15-14 3-10 12-17 23-17 13 0 24 9 27 21 8 0 15 6 15 14 0 8-7 14-15 14H34c-9 0-16-7-16-18z" fill="#eef3f8" stroke="#cbd5df" stroke-width="2"/>':'<circle cx="40" cy="40" r="20" fill="#ffe45b"/><g stroke="#ffe45b" stroke-width="4" stroke-linecap="round"><path d="M40 8v9M40 63v9M8 40h9M63 40h9M18 18l7 7M55 55l7 7M62 18l-7 7M25 55l-7 7"/></g>';return`<svg class="modern-weather-icon" viewBox="0 0 112 92" aria-hidden="true">${c}</svg>`}
function updateWeatherIcon(){const el=document.getElementById('weatherIcon');if(!el)return;const condition=text('condition').toLowerCase();if(!condition||condition==='weather needs data')return;const h=new Date().getHours(),night=h<6||h>=18,cloudy=/cloud|overcast|fog|rain|drizzle|shower|thunder|snow/.test(condition),svg=night?moonSVG(moonPhase(),cloudy):daySVG(cloudy);if(el.innerHTML!==svg)el.innerHTML=svg;el.title=night?'Night • moon phase and weather':'Daytime • weather'}
function setWeatherExtraLabels(){const cards=document.querySelectorAll('.weather-grid .metric');if(cards.length<9)return;const al=cards[7].querySelector('.metric-label'),pl=cards[8].querySelector('.metric-label');if(al)al.innerHTML='AQI <span class="metric-icon">●</span>';if(pl)pl.innerHTML='Air Pressure <span class="metric-icon">▣</span>'}
function aqiQuality(n){if(!Number.isFinite(n))return'';if(n<=50)return'Good';if(n<=100)return'Moderate';if(n<=150)return'Unhealthy SG';if(n<=200)return'Unhealthy';if(n<=300)return'Very Unhealthy';return'Hazardous'}
async function fetchWeatherExtras(lat,lon){const aqiEl=document.getElementById('aqi'),pressureEl=document.getElementById('pressure');if(!aqiEl||!pressureEl)return;const w=new URL('https://api.open-meteo.com/v1/forecast');w.searchParams.set('latitude',lat);w.searchParams.set('longitude',lon);w.searchParams.set('current','surface_pressure');w.searchParams.set('timezone','auto');const aq=new URL('https://air-quality-api.open-meteo.com/v1/air-quality');aq.searchParams.set('latitude',lat);aq.searchParams.set('longitude',lon);aq.searchParams.set('current','us_aqi');aq.searchParams.set('timezone','auto');const results=await Promise.allSettled([fetch(w,{cache:'no-store'}),fetch(aq,{cache:'no-store'})]);const wr=results[0],ar=results[1];try{if(wr.status==='fulfilled'&&wr.value.ok){const j=await wr.value.json(),p=Number(j?.current?.surface_pressure);if(Number.isFinite(p)){pressureEl.textContent=Math.round(p)+' mbar';pressureEl.dataset.weatherBound='1'}}}catch(e){}try{if(ar.status==='fulfilled'&&ar.value.ok){const j=await ar.value.json(),n=Number(j?.current?.us_aqi);if(Number.isFinite(n)){aqiEl.textContent=Math.round(n)+' '+aqiQuality(n);aqiEl.dataset.weatherBound='1'}}}catch(e){}}
function watchWeatherExtras(){setWeatherExtraLabels();let last='';let busy=false;const tick=()=>{const la=text('lat').replace(/[^0-9.-]/g,''),lo=text('lon').replace(/[^0-9.-]/g,'');if(!la||!lo||la==='—'||lo==='—')return;const key=la+','+lo;if(key!==last)last=key;if(busy)return;const a=document.getElementById('aqi'),p=document.getElementById('pressure');if(a?.dataset.weatherBound==='1'&&p?.dataset.weatherBound==='1')return;busy=true;fetchWeatherExtras(Number(la),Number(lo)).finally(()=>busy=false)};tick();setTimeout(tick,2000);setTimeout(tick,7000);setTimeout(tick,15000);setInterval(tick,60000)}
function watchWeatherIcon(){updateWeatherIcon();setInterval(updateWeatherIcon,1000);const condition=document.getElementById('condition');if(condition&&window.MutationObserver)new MutationObserver(()=>setTimeout(updateWeatherIcon,0)).observe(condition,{childList:true,characterData:true,subtree:true})}
function start(){ensureCountryLine();setInterval(ensureCountryLine,400);fitDashboardText();setWeatherExtraLabels();if(window.ResizeObserver){const ro=new ResizeObserver(fitDashboardText);document.querySelectorAll('.position-grid,.weather-grid,.weather-main').forEach(el=>ro.observe(el))}setInterval(fitDashboardText,1000);watchWeatherIcon();watchWeatherExtras()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()})();